# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 519e5dfbb0c12e71e89884acf4f418667a598cd68a5db2d499b2d1666796f8b87b508f3cbab721bff2886db44344538c7baa5b5ede9dadafc0b866e6bc8b0629

test:
  secret_key_base: 730dbaa75c7c6528f1180c4e31145321e29eb3467640e3ffe291b8ac0a4b6c954d72cf89c10ce7a031901ed96fe767d829387e41d268df398a7087cbdfc22b23

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
